### ISSUE TITLE
Clicking on test badge just leads to a picture

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse-kuksa/kuksa-android-sdk#102]
There are some badges in main Readme among them a testing badge

![image](https://github.com/eclipse-kuksa/kuksa-android-sdk/assets/3707124/2273f718-c91a-443d-9d8d-27700f6cf2e2)

Those badges are all "clickable", License badge brings you to the Apache license, Chat badge brings you to the gitter chat. Clicking the test result badge, just brings you to a picture of the badge, i.e. this is the result

![image](https://github.com/eclipse-kuksa/kuksa-android-sdk/assets/3707124/a22dc4f5-9e10-49c0-8157-8f5a345ee448)

I think the badge either should be non-clickable or lead to the latest test run.

For reference this is what https://github.com/eclipse/kuksa.val/blob/master/README.md is linking

https://github.com/eclipse/kuksa.val/actions/workflows/kuksa_databroker_build.yml?query=branch%3Amaster

Not sure this pattern is the "best" way, but would be "better"

**Comment by wba2hi** [comment]
Yes, you are right. This way it is easier to check what went wrong. 

I aligned it in the linked PR :)
