### ISSUE TITLE
Add unsubscribe API 

### ISSUE THREAD

**Issue by Chrylo** [eclipse-kuksa/kuksa-android-sdk#18]
**Is your feature request related to a problem? Please describe.**
The DataBrokerConnection has no unsubscribe functionality currently.

**Describe the solution you'd like**
Similar to the subscribe API, add the counterpart unsubscribe for specifications and properties.

**Comment by wba2hi** [comment]
Unsubscribing can be done by simply closing the Stream returned by the SubscribeRequest
