### ISSUE TITLE
Align Terminology of Model Classes / Public API

### ISSUE THREAD

**Issue by wba2hi** [eclipse-kuksa/kuksa-android-sdk#70]
**Is your feature request related to a problem? Please describe.**
Our terminology used inside the SDK is not consistent to the "real world". While the "VSS Specification" contains a list of all Vehicle Signals, we have a base class named "VssSpecification". All our generated classes extend this "VssSpecification". 
While it's true, that each of these classes are part of the VssSpecification each element on it's own is not the "VssSpecification". 

Same with the annotation. The only annotation which is used to reference the VssSpecification file is named "VssDefinition". While this is a valid name, a more appropriate name would be "VssSpecification".

PropertyListener also is chosen arbitrarily but it also probably needs the same name

The naming "VssSpecification is also redundant as VSS means "Vehicle Signal Specification". Therefore A VssSpecification is a "Vehicle Signal Specification Specification" :D 

**Describe the solution you'd like**
- Rename VssDefinition -> Vs(s)Specification
- Rename VssSpecification -> VssSignal / VssElement / VssNode / ...
- Rename VssSpecificationListener -> VssSignalListener (?)
- Rename PropertyListener -> VssSignalListener (?)
- check other models for inconsistencies with "common names"

**Comment by Chrylo** [comment]
**Renaming:** 
VssDefinition (Annotation) -> VssModelGenerator
VssNode (Any node with vss childs / parents) -> VssNode  
VssSpecification (Any node + vss information) -> Removed /  merged with VssNode
VssProperty (Leaf) -> VssLeaf

VssSpecificationListener -> VssNodeListener
PropertyListener -> VssPathListener
SpecificationPropertyListener -> VssNodePathListener
Property -> Removed / Replaced with:
```
interface DataBrokerRequest {
    vssPath: String
    fields: Collection<Field>
}
FetchRequest : DatabrokerRequest
SubscribeRequest : DatabrokerRequest
UpdateRequest : DatabrokerRequest {
    dataPoint: DataPoint
}
VssNodeDataBrokerRequest : DataBrokerRequest<T : Node> {
    vssNode: T
}
VssNodeFetchRequest : VssNodeDataBrokerRequest
VssNodeUpdateRequest : VssNodeDataBrokerRequest 
VssNodeSubscribeRequest : VssNodeDataBrokerRequest
```

**Checked:**
- Tests
- Diagrams (puml)
- Main code
- Guides 
- Kdoc

**Tested:**
- Get / Set / Subscribe via Vss paths + generated Models (Tested model Vehicle.Speed)


It is easy to miss naming like "property" etc.  in the documentation / guides and so on. So please have a good look also.
