### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by mikehaller** [eclipse-kuksa/kuksa-android-sdk#76]
I'd like to authenticate to the Kuksa databroker using tokens.
Is there any documentation or example available?

Reference
- https://github.com/eclipse/kuksa.val/blob/master/doc/system-architecture.md

**Comment by wba2hi** [comment]
@mikehaller 
Authentication was added with the linked PR.

The JsonWebToken can (optionally) be provided to the DataBrokerConnector of the SDK. 
```
val jsonWebToken = JsonWebToken("someValidJwt") 
val connector = DataBrokerConnector(managedChannel, jsonWebToken)
```

However, it can also be removed / replaced during an active Connection by simply setting a new one in the DataBrokerConnection:
```
val newJsonWebToken = JsonWebToken("someValidJwt") 
dataBrokerConnection.jsonWebToken = newJsonWebToken
```
Samples, documentation etc was adapted
