### ISSUE TITLE
 Add automatic changelog generation

### ISSUE THREAD

**Issue by wba2hi** [eclipse-kuksa/kuksa-android-sdk#9]
**Is your feature request related to a problem? Please describe.**
The project is already using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). This can be used to automatically generate a changelog.

**Describe the solution you'd like**
- The changelog should automatically be deployed (if deployment is already implemented)
- A command (npm/yarn or similiar) should be available to generate a changelog of the current version

**Comment by Chrylo** [comment]
Was done in #26
