### ISSUE TITLE
Fix Uint not supported by VSS model generation

### ISSUE THREAD

**Issue by Chrylo** [eclipse-kuksa/kuksa-android-sdk#93]
**Describe the bug**
VSS file models which have an Uint defined are currently converted to an Int data type. However the grpc protocol expects an Uint hence no updates are send successfully. 

**To Reproduce**
1. Send an update to the DataBroker via a generated model (should be uInt but is int) e.g. VssHeartRate

**Expected behavior**
A successful update

**Screenshots**
<img width="2056" alt="Screenshot 2024-03-06 at 11 19 14" src="https://github.com/eclipse-kuksa/kuksa-android-sdk/assets/1355532/c7c29621-0154-4404-9923-559d37318069">
<img width="677" alt="Screenshot 2024-03-06 at 11 16 58" src="https://github.com/eclipse-kuksa/kuksa-android-sdk/assets/1355532/e080198e-cd10-4527-9901-5ef8edaccc76">

**Additional context**

The following generated model does not support Uint + @JvmOverloads because Uint is defined as an inline/value class. Removing the @JvmOverloads will break the generation via reflection of the model classes.
```
data class VssHeartRate @JvmOverloads constructor(
        override val `value`: Uint = 0,
) : VssLeaf<Uint> {
```

- Can be easily reproduced with the DataBrokerConnectionTests when changing the updates from VSSPath mode to VSSNode mode: 
e.g.: The initial value is different from the default for a child / Every child node has been updated with the correct value
- Check for other non supported types.

**Comment by wba2hi** [comment]
UInt64 is mapped to a generic Long, I could imagine this also making some issues - should be checked as well
